# TCL File Generated by Component Editor 11.1sp2
# Sun Mar 27 11:50:23 EDT 2016
# DO NOT MODIFY


# +-----------------------------------
# | 
# | processor "processor" v1.0
# | null 2016.03.27.11:50:23
# | 
# | 
# | C:/Users/Tommy/workspaces/Quartus II/lab6/SOPC/processor.v
# | 
# |    ./processor.v syn, sim
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 11.0
# | 
package require -exact sopc 11.0
# | 
# +-----------------------------------

# +-----------------------------------
# | module processor
# | 
set_module_property NAME processor
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property DISPLAY_NAME processor
set_module_property TOP_LEVEL_HDL_FILE processor.v
set_module_property TOP_LEVEL_HDL_MODULE processor
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL TRUE
set_module_property STATIC_TOP_LEVEL_MODULE_NAME processor
set_module_property FIX_110_VIP_PATH false
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file processor.v {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | display items
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point conduit_end
# | 
add_interface conduit_end conduit end

set_interface_property conduit_end ENABLED true

add_interface_port conduit_end Done export Output 1
add_interface_port conduit_end Run export Input 1
add_interface_port conduit_end p_Q export Output 16
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock_sink
# | 
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 0

set_interface_property clock_sink ENABLED true

add_interface_port clock_sink Clock clk Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock_sink_reset
# | 
add_interface clock_sink_reset reset end
set_interface_property clock_sink_reset associatedClock clock_sink
set_interface_property clock_sink_reset synchronousEdges DEASSERT

set_interface_property clock_sink_reset ENABLED true

add_interface_port clock_sink_reset Resetn reset_n Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point avalon_master
# | 
add_interface avalon_master avalon start
set_interface_property avalon_master addressUnits SYMBOLS
set_interface_property avalon_master associatedClock clock_sink
set_interface_property avalon_master associatedReset ""
set_interface_property avalon_master burstOnBurstBoundariesOnly false
set_interface_property avalon_master doStreamReads false
set_interface_property avalon_master doStreamWrites false
set_interface_property avalon_master linewrapBursts false
set_interface_property avalon_master readLatency 0

set_interface_property avalon_master ENABLED true

add_interface_port avalon_master avalon_wait_request waitrequest Input 1
add_interface_port avalon_master avalon_address address Output 32
add_interface_port avalon_master avalon_writedata writedata Output 32
add_interface_port avalon_master avalon_byteenable byteenable Output 4
add_interface_port avalon_master avalon_read read Output 1
add_interface_port avalon_master avalon_write write Output 1
add_interface_port avalon_master avalon_readdata readdata Input 32
# | 
# +-----------------------------------
