# TCL File Generated by Component Editor 11.1sp2
# Sun Mar 27 15:18:42 EDT 2016
# DO NOT MODIFY


# +-----------------------------------
# | 
# | peripheral "peripheral" v1.0
# | null 2016.03.27.15:18:42
# | 
# | 
# | C:/Users/Tommy/workspaces/Quartus II/lab6/part7/peripheral/peripheral.v
# | 
# |    ./peripheral.v syn, sim
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 11.0
# | 
package require -exact sopc 11.0
# | 
# +-----------------------------------

# +-----------------------------------
# | module peripheral
# | 
set_module_property NAME peripheral
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property DISPLAY_NAME peripheral
set_module_property TOP_LEVEL_HDL_FILE peripheral.v
set_module_property TOP_LEVEL_HDL_MODULE peripheral
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL TRUE
set_module_property STATIC_TOP_LEVEL_MODULE_NAME peripheral
set_module_property FIX_110_VIP_PATH false
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file peripheral.v {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | display items
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clockreset
# | 
add_interface clockreset clock end
set_interface_property clockreset clockRate 0

set_interface_property clockreset ENABLED true

add_interface_port clockreset csi_clockreset_clk clk Input 1
add_interface_port clockreset csi_clockreset_reset reset Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point s1
# | 
add_interface s1 avalon end
set_interface_property s1 addressAlignment DYNAMIC
set_interface_property s1 addressUnits WORDS
set_interface_property s1 associatedClock clockreset
set_interface_property s1 burstOnBurstBoundariesOnly false
set_interface_property s1 explicitAddressSpan 0
set_interface_property s1 holdTime 0
set_interface_property s1 isMemoryDevice false
set_interface_property s1 isNonVolatileStorage false
set_interface_property s1 linewrapBursts false
set_interface_property s1 maximumPendingReadTransactions 0
set_interface_property s1 printableDevice false
set_interface_property s1 readLatency 0
set_interface_property s1 readWaitTime 1
set_interface_property s1 setupTime 0
set_interface_property s1 timingUnits Cycles
set_interface_property s1 writeWaitTime 0

set_interface_property s1 ENABLED true

add_interface_port s1 avs_s1_chipselect chipselect Input 1
add_interface_port s1 avs_s1_address address Input 3
add_interface_port s1 avs_s1_read read Input 1
add_interface_port s1 avs_s1_write write Input 1
add_interface_port s1 avs_s1_writedata writedata Input 32
add_interface_port s1 avs_s1_readdata readdata Output 32
add_interface_port s1 avs_s1_waitrequest waitrequest Output 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point conduit_end_0
# | 
add_interface conduit_end_0 conduit end

set_interface_property conduit_end_0 ENABLED true

add_interface_port conduit_end_0 coe_vga_LEDG export Output 9
add_interface_port conduit_end_0 coe_vga_VGA_R export Output 10
add_interface_port conduit_end_0 coe_vga_VGA_G export Output 10
add_interface_port conduit_end_0 coe_vga_VGA_B export Output 10
add_interface_port conduit_end_0 coe_vga_VGA_HS export Output 1
add_interface_port conduit_end_0 coe_vga_VGA_VS export Output 1
add_interface_port conduit_end_0 coe_vga_VGA_BLANK export Output 1
add_interface_port conduit_end_0 coe_vga_VGA_SYNC export Output 1
add_interface_port conduit_end_0 coe_vga_VGA_CLK export Output 1
# | 
# +-----------------------------------
